name: Validate Module
on:
  # Run when a push or pull request contains changes in the module directory.
  push:
    paths:
      - module/**
  pull_request:
    paths:
      - module/**
jobs:
  main:
    name: Validate Module
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      # Cache Node Module Dependencies
      - name: Cache Node Module Dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: nodemodules-${{ runner.os }}-${{ hashFiles('module/package-lock.json') }}
      # Install Dependencies
      - name: Install Dependencies
        run: npm install
      # Lint Code
      - name: Lint Code
        run: npm run lint
      # Compile Source
      - name: Compile Source
        run: npm run compile
